networkPolicy:
  enabled: true
  ingress:
    namespaceSelector: {}
    podSelector: {}

verticalPodAutoscaler:
  enabled: true

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: ""

image:
  registry: &registry quay.io
#   repository: giantswarm/trivy

trivy:
  rbac:
    pspEnabled: true
  image:
    registry: *registry
    repository: giantswarm/trivy
    # Tag must also be updated to match in trivy-operator-app
    # If not set here, the image version is taken from the appVersion of the upstream chart.
  service:
    port:
  modules:
    enabled: false
    urls:
    - ghcr.io/aquasecurity/trivy-module-spring4shell
  securityContext:
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
