networkPolicy:
  enabled: true
  ingress:
    namespaceSelector: {}
    podSelector: {}

ciliumNetworkPolicy:
  enabled: true

verticalPodAutoscaler:
  trivy:
    enabled: true
    containerPolicies: {}

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true
  namespace: giantswarm

trivy:
  rbac:
    pspEnabled: false
  image:
    registry: gsoci.azurecr.io
    repository: giantswarm/trivy
    # Tag must also be updated to match in trivy-operator-app
    # If not set here, the image version is taken from the appVersion of the upstream chart.
  labels:
    application.giantswarm.io/team: "shield"
  service:
    port:
  modules:
    enabled: false
    urls:
      - ghcr.io/aquasecurity/trivy-module-spring4shell
  securityContext:
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
  
  trivy:
    dbRepository: gsoci.azurecr.io/giantswarm/trivy-db
