networkPolicy:
  enabled: true
  ingress:
    namespaceSelector: {}
    podSelector: {}

verticalPodAutoscaler:
  enabled: true

trivy:
  rbac:
    pspEnabled: true
  image:
    registry: docker.io
    repository: giantswarm/trivy
    # Tag must also be updated to match in trivy-operator-app
    # If not set here, the image version is taken from the appVersion of the upstream chart.
  service:
    port:
  modules:
    enabled: false
    urls:
    - ghcr.io/aquasecurity/trivy-module-spring4shell

ciliumNetworkPolicy:
  enabled: false
