networkPolicy:
  enabled: false
  ingress:
    namespaceSelector: {}
    podSelector: {}

verticalPodAutoscaler:
  enabled: true

# Enable Kyverno PolicyException
kyvernoPolicyExceptions:
  enabled: true

pspAnnotations:
  seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'runtime/default'

trivy:
  rbac:
    pspEnabled: true
  image:
    registry: docker.io
    repository: giantswarm/trivy
    # Tag must also be updated to match in trivy-operator-app
    # If not set here, the image version is taken from the appVersion of the upstream chart.
  service:
    port:
  modules:
    enabled: false
    urls:
    - ghcr.io/aquasecurity/trivy-module-spring4shell
  securityContext:
    privileged: false
    readOnlyRootFilesystem: true
    allowPrivilegeEscalation: false
    seccompProfile:
      type: RuntimeDefault
  podSecurityContext:
    runAsUser: 65534
    runAsNonRoot: true
    fsGroup: 65534
    seccompProfile:
      type: RuntimeDefault
