apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: helm/trivy/charts
  contents:
  - path: .
    git:
      url: https://github.com/giantswarm/trivy-upstream
      ref: v0.64.1
    includePaths:
      - helm/**/*
    newRootPath: helm
