apiVersion: v2
appVersion: 0.0.1
annotations:
  application.giantswarm.io/team: "ludacris"
  config.giantswarm.io/version: 1.x.x
description: A Helm chart for trivy
engine: gotpl
home: https://github.com/giantswarm/trivy-app
icon: https://s.giantswarm.io/app-icons/1/png/default-app-light.png
maintainers:
- name: Giant Swarm applications team
  url: https://github.com/giantswarm/trivy-app
name: trivy-app
sources:
- https://github.com/giantswarm/trivy-app
version: [[ .Version ]]

dependencies:
- name: trivy
  version: 0.4.4
