trivy:
  image:
    registry: docker.io
    repository: giantswarm/trivy
    # Tag must also be updated in starboard-app
    # If not set here, the image version is taken from the appVersion of the upstream chart.
    # tag: 0.24.0

  networkPolicy:
    enabled: true
    ingress:
      namespaceSelector: {}
      podSelector: {}
