{{- if .Values.kyvernoPolicyExceptions.enabled }}
  {{- if .Capabilities.APIVersions.Has "kyverno.io/v2alpha1/PolicyException" -}}
apiVersion: kyverno.io/v2alpha1
kind: PolicyException
metadata:
  name: {{ include "trivy.fullname" . }}-exception
  namespace: {{ .Release.Namespace }}
spec:
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
    - require-drop-all
    - autogen-require-drop-all
  - policyName: disallow-privilege-escalation
    ruleNames:
    - privilege-escalation
    - autogen-privilege-escalation
  - policyName: restrict-seccomp-strict
    ruleNames:
    - check-seccomp-strict
    - autogen-check-seccomp-strict
  match:
    any:
    - resources:
        kinds:
        - StatefulSet
        - Pod
        namespaces:
        - {{ .Release.Namespace }}
        names:
        - {{ include "trivy.fullname" . }}
        - {{ include "trivy.fullname" . }}-*
  {{- end -}}
{{- end -}}
