{{- if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" -}}
{{- if .Values.verticalPodAutoscaler.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "trivy.fullname" . }}-vpa
  labels:
    {{- include "trivy.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - controlledResources:
      {{- range .Values.verticalPodAutoscaler.controlledResources}}
        - {{.}}
      {{end -}}
      maxAllowed:
        cpu: {{ .Values.verticalPodAutoscaler.maxAllowed.cpu }}
        memory: {{ .Values.verticalPodAutoscaler.maxAllowed.memory }}
      minAllowed:
        cpu: {{ .Values.verticalPodAutoscaler.minAllowed.cpu }}
        memory: {{ .Values.verticalPodAutoscaler.minAllowed.memory }}
      # mode: Auto
      containerName: main
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       {{ include "trivy.fullname" . }}
  updatePolicy:
    updateMode: {{ .Values.verticalPodAutoscaler.updateMode }}
{{- end -}}
{{- end -}}
