{{- if .Capabilities.APIVersions.Has "autoscaling.k8s.io/v1" -}}
{{- if .Values.verticalPodAutoscaler.trivy.enabled -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "trivy.fullname" . }}-vpa
  labels:
    {{- include "trivy.labels" . | nindent 4 }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: 'main'
    {{- if .Values.verticalPodAutoscaler.trivy.containerPolicies }}
      {{- with .Values.verticalPodAutoscaler.trivy.containerPolicies -}}
        {{ tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
    {{- end }}
  targetRef:
    apiVersion: "apps/v1"
    kind:       StatefulSet
    name:       {{ include "trivy.fullname" . }}
  updatePolicy:
    updateMode: Auto
{{- end -}}
{{- end -}}
