version: 2.1
orbs:
  architect: giantswarm/architect@5.14.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-trivy-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "trivy"
          executor: "app-build-suite"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-trivy-to-giantswarm-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "trivy"
          executor: "app-build-suite"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-trivy-to-giantswarm-catalog

      # Push trivy to app collections
      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-to-aws-app-collection
          app_name: "trivy"
          app_collection_repo: "aws-app-collection"
          requires:
            - push-trivy-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-to-azure-app-collection
          app_name: "trivy"
          app_collection_repo: "azure-app-collection"
          requires:
            - push-trivy-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-to-capa-app-collection
          app_name: "trivy"
          app_collection_repo: "capa-app-collection"
          requires:
            - push-trivy-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-to-capz-app-collection
          app_name: "trivy"
          app_collection_repo: "capz-app-collection"
          requires:
            - push-trivy-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-to-cloud-director-app-collection
          app_name: "trivy"
          app_collection_repo: "cloud-director-app-collection"
          requires:
            - push-trivy-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-to-proxmox-app-collection
          app_name: "trivy"
          app_collection_repo: "proxmox-app-collection"
          requires:
            - push-trivy-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/

      - architect/push-to-app-collection:
          context: "architect"
          name: push-trivy-to-vsphere-app-collection
          app_name: "trivy"
          app_collection_repo: "vsphere-app-collection"
          requires:
            - push-trivy-to-control-plane-catalog
          filters:
            # Only do this when a new tag is created.
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
