version: 2.1
orbs:
  architect: giantswarm/architect@6.15.0

workflows:
  package-and-push-chart-on-tag:
    jobs:
      - architect/push-to-app-catalog:
          context: "architect"
          name: push-trivy-to-control-plane-catalog
          app_catalog: "control-plane-catalog"
          app_catalog_test: "control-plane-test-catalog"
          chart: "trivy"
          executor: "app-build-suite"
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: "architect"
          name: push-trivy-to-giantswarm-catalog
          app_catalog: "giantswarm-catalog"
          app_catalog_test: "giantswarm-test-catalog"
          chart: "trivy"
          executor: "app-build-suite"
          persist_chart_archive: true
          # Trigger job on git tag.
          filters:
            tags:
              only: /^v.*/

      - architect/push-to-app-catalog:
          context: architect
          executor: app-build-suite
          name: push-trivy-chart-to-default-catalog
          app_catalog: default-catalog
          app_catalog_test: default-test-catalog
          persist_chart_archive: true
          chart: trivy
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore:
              - main

      - architect/run-tests-with-ats:
          name: execute chart tests
          filters:
            # Do not trigger the job on merge to master.
            branches:
              ignore:
                - master
          requires:
            - push-trivy-to-giantswarm-catalog
