---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trivy.fullname" . }}-egress-dns
  labels:
    {{- include "trivy.labels" . | nindent 4 }}
spec:
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "trivy.selectorLabels" . | nindent 6 }}
  egress:
    - ports:
        - port: 53
          protocol: UDP
      to:
        - namespaceSelector: {}

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "trivy.fullname" . }}-egress-external
  labels:
    {{- include "trivy.labels" . | nindent 4 }}
spec:
  egress:
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
          # except:
          #   - 10.0.0.0/8
          #   - 172.16.0.0/12
          #   - 192.168.0.0/16
  policyTypes:
    - Egress
  podSelector:
    matchLabels:
      {{- include "trivy.selectorLabels" . | nindent 6 }}
